name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ghga-devutil
        run: pip install git+https://github.com/ghga-de/ghga-devutil.git@main
      
      - name: Install hugo
        run: sudo apt-get install -y hugo 
        
      - name: Run ghga-devutil to build web content
        run: ghga-devutil html services/*.yaml html
      
      - name: Build site
        run: cd html && hugo --theme hugo-book

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html/public
