name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ghga-devutil
        run: pip install git+https://github.com/ghga-de/ghga-devutil.git@main
      
      - name: Install hugo
        run: sudo apt-get install -y hugo 

      - name: Load hugo theme
        run: mkdir -p html/themes && git clone --depth 1 -b master https://github.com/alex-shpak/hugo-book html/themes/hugo-book

      - name: Generate markdown files from yaml
        run: mkdir -p html/content/docs/services && ghga-devutil markdown services/*.yaml html/content/docs/services
      
      - name: Build site
        run: cd html && hugo --theme hugo-book

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html/public
